### add new consultant

POST http://localhost:5000/consultant
Content-Type: application/json

{
    "email":"andrius@gmail.com",
    "password":"cool",
    "isLoggedIn": false,
    "isActive": false,
    "visits": []
}

### add new consultant

POST http://localhost:5000/consultant
Content-Type: application/json

{
    "email":"nfq@gmail.com",
    "password":"cool",
    "isLoggedIn": false,
    "isActive": false,
    "visits": []
}

