### add new costumer

POST http://localhost:5000/addNewCostumer
Content-Type: application/json

{
    "reference":"123456",
    "active":false
}

### get all costumers

GET http://localhost:5000/allCostumers


### delete one costumer

DELETE http://localhost:5000/delete/61af567e515e71634089ffa5


###update costumer visit status

PUT http://localhost:5000/edit/61af9c8b3c75bb056412198f
Content-Type: application/json

{
    "active":true
}